# Generated by Django 6.0.3 on 2026-03-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('users', '0007_buyerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='buyer',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.buyerprofile'),
            preserve_default=False,
        ),
    ]
