# Generated by Django 6.0.3 on 2026-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('north', 'North'), ('east', 'East'), ('west', 'West'), ('south', 'South')], max_length=20, unique=True)),
                ('wilayas', models.JSONField(default=list, help_text='List of wilayas in this region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
    ]
