# Generated by Django 6.0.3 on 2026-03-30 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_prices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='officialprice',
            name='official_pr_product_ba49d5_idx',
        ),
        migrations.AddField(
            model_name='officialprice',
            name='region',
            field=models.CharField(blank=True, help_text="e.g., 'north', 'south'. Leave blank for national or specific wilaya.", max_length=50),
        ),
        migrations.AlterField(
            model_name='officialprice',
            name='wilaya',
            field=models.CharField(blank=True, help_text='Empty = national or region-wide price', max_length=100),
        ),
        migrations.AddIndex(
            model_name='officialprice',
            index=models.Index(fields=['product_name', 'wilaya', 'region'], name='official_pr_product_f6727c_idx'),
        ),
    ]
